#stage 1: Build the Angular app
FROM node:22.2.0 as build
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli
COPY . .
RUN ng build

#stage 2: serve the app with nginx
FROM nginx:latest
COPY --from=build app/dist/angular-play/browser /usr/share/nginx/html
EXPOSE 80
